// Rails 8 Stimulus controllers auto-loading
// This file is auto-generated by the Stimulus generator

import { application } from "./application"

// Import all controllers
import CustomerFormController from "./customer_form_controller"

// Register controllers
application.register("customer-form", CustomerFormController)