version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Japan
  reviewers:
    - "kakikubo"
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: disabled
