version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Japan
  reviewers:
    - "kakikubo"
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: disabled
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: "08:00"
    timezone: Japan
  open-pull-requests-limit: 10
  assignees:
    - kakikubo
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  labels:
    - "GH Actions"
    - "dependencies"
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  assignees:
    - mpg-kosuke-toyama
    - mpg-tetsuto-aizawa
    - mpg-teruo-kakikubo
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  labels:
    - "dependencies"
