require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
inherit_from: .rubocop_todo.yml

# Offense count: 1
# Cop supports --auto-correct.
Layout/LeadingEmptyLines:
  Exclude:
    - 'spec/experiments/string_spec.rb'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Naming/VariableNumber:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
