require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
inherit_from: .rubocop_todo.yml

# Offense count: 1
# Cop supports --auto-correct.
Layout/LeadingEmptyLines:
  Exclude:
    - 'spec/experiments/string_spec.rb'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Naming/VariableNumber:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 86

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 41

Metrics/PerceivedComplexity:
  Max: 14

RSpec/ExampleLength:
  Max: 35

RSpec/MultipleExpectations:
  Max: 5
