# PostgreSQL. Versions 12 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['PGSQL_HOST'] || 'db' %>
  port: <%= ENV['PGSQL_PORT'] || '5432' %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  
  # Rails 8 performance optimizations
  prepared_statements: true
  advisory_locks: true
  
  # Rails 8 connection pool optimizations
  checkout_timeout: 5
  reaping_frequency: 10
  
  # Rails 8 query optimizations
  query_cache: true
  
  # Rails 8 connection management
  idle_timeout: 300
  
  # Rails 8 statement timeout for better performance
  statement_timeout: 30000

development:
  <<: *default
  database: baukis2_development
  
  # Rails 8 development optimizations
  # Enable query logging for development debugging
  min_messages: notice
  
  # Development-specific connection pool settings
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: baukis2

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: baukis2_test
  
  # Rails 8 test environment optimizations
  # Faster test database connections
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  
  # Reduced timeouts for faster test execution
  timeout: 1000
  checkout_timeout: 2
  
  # Test-specific optimizations
  prepared_statements: false  # Disable for test isolation
  query_cache: false         # Disable for test consistency

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: baukis2_production
  username: baukis2
  password: <%= ENV['BAUKIS2_DATABASE_PASSWORD'] %>
  
  # Rails 8 production optimizations
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 10000
  
  # Production-specific connection management
  checkout_timeout: 10
  reaping_frequency: 5
  
  # Production performance optimizations
  query_cache: true
  prepared_statements: true
  
  # Production connection limits
  idle_timeout: 600
  statement_timeout: 60000
