name: erb-lint

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  erb-lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: test
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
      - name: Run erblint
        run: bundle exec erblint --lint-all
