name: erb-lint

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  erb-lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: lint
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Run erblint
        run: bundle exec erblint --lint-all
