name: rubocop

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: x.x.x # .ruby-version を参照する
          bundler-cache: true
      - name: Run rubocop and add rubocop comment
        uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true
          use_bundler: true
          github_token: ${{ github.token }}
          rubocop_flags: --parallel
          reporter: github-pr-review
